input_manifest: bench_fr/manifest_wer_fr.jsonl
output_folder: bench_fr/local_bench_fr
input_audios_paths: /home/abert/Linagora/parakeet/datasets/nemo_dataset/converted_audios/%n_%s
compute_rtf: False
plot_monitoring: False
skip_errors: False

benchmarks:
  - backend: http-api
    model: linagora_kaldi
    device: cpu
    am_model: linSTT_AM_fr-FR_v2.2.0
    lm_model: decoding_graph_fr-FR_Big_v3.0.0
  - backend: nemo
    model: 
    - nvidia/canary-1b
    batch_size: 8
  - backend: nemo
    model: 
    - nvidia/stt_fr_fastconformer_hybrid_large_pc
    - bofenghuang/stt_fr_fastconformer_hybrid_large
    - /mnt/d/linagora/models/stt_fr_fastconformer_hybrid_large_finetuned_v2.nemo
    batch_size: 8
    decoder: 
    # - ctc
    - rnnt
  - backend: faster-whisper
    model: 
    - large-v3
    - large-v3-turbo
    - bofenghuang/whisper-large-v3-french
    - bofenghuang/whisper-large-v3-french-distil-dec8
    precision: float16
  # - backend: transformers-facebook
  #   vad: false
  #   model: facebook/mms-1b-all
  # - backend: transformers-bofenghuang
  #   vad: false
  #   model: bofenghuang/asr-wav2vec2-ctc-french